# Generated by Django 3.0.2 on 2020-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('phone', models.IntegerField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
