# Generated by Django 3.0.2 on 2020-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
